### ISSUE TITLE
Feature: automatic generation of figure puzzles.

### ISSUE THREAD

**Issue by timthedev07** [brianyu28/puzzles#1]
I'm thinking of replacing the manual process of generating puzzles with a serverless function on Cloudflare that is connected to a Redis labs instance. I can create a separate repository for that, and I think this would potentially save a lot of time.

**Comment by lablnet** [comment]
`GitHub Actions` can be used for that, It can also be sechuled and the json file can push to current repo.

Now for being `serverless` we do not need any kind of other third party `vendor` for simple and that type of work.
